print("Content-Type: text/html")
print()

print("<html>")
print("<head>")
print("<title>Welcome to RikaKawai><</title>")
print("<style>")
print("body {")
print("    background-color: black;")
print("    color: lime;")
print("    font-family: monospace;")
print("    text-align: center;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<h1>RikaKawai><</h1>")
print("<p>This is a hacker-style Python script with a header!</p>")
print("</body>")
print("</html>")
